return {
  logLevel = "info",
  notifications = {
    enabled = true,
  },
  reload = {
    watchConfigDir = true,
    hotkey = { { "cmd", "alt", "ctrl" }, "R" },
  },
  windowTiling = {
    enabled = true,
    screenMargin = 8,
    windowMargin = 8,
    centerSize = { w = 0.64, h = 0.82 },
    hotkeys = {
      left = { { "ctrl", "alt" }, "Left" },
      right = { { "ctrl", "alt" }, "Right" },
      top = { { "ctrl", "alt" }, "Up" },
      bottom = { { "ctrl", "alt" }, "Down" },
      topLeft = { { "ctrl", "alt", "cmd" }, "Left" },
      topRight = { { "ctrl", "alt", "cmd" }, "Right" },
      bottomLeft = { { "ctrl", "alt", "cmd" }, "Down" },
      bottomRight = { { "ctrl", "alt", "cmd" }, "Up" },
      maximize = { { "ctrl", "alt" }, "Return" },
      center = { { "ctrl", "alt" }, "C" },
      nextScreen = { { "ctrl", "alt" }, "N" },
      previousScreen = { { "ctrl", "alt" }, "P" },
    },
  },
  keystrokes = {
    enabled = true,
    notifyOnShellFinish = false,
    hotkeys = {
      {
        mods = { "ctrl", "alt", "cmd" },
        key = "I",
        description = "Open iTerm",
        action = { type = "app", name = "iTerm" },
      },
      {
        mods = { "ctrl", "alt", "cmd" },
        key = "L",
        description = "Lock screen",
        action = { type = "hs", command = "lockScreen" },
      },
      {
        mods = { "ctrl", "shift" },
        key = "1",
        description = "Switch Dell monitor",
        action = { type = "shell", command = "bash ~/Scripts/switch-dell-monitor.sh" },
      },
    },
  },
  awake = {
    enabled = true,
    whenExternalDisplay = true,
    requireClamshell = true,
    requireACPower = true,
    preventDisplaySleep = false,
    showNotifications = true,
    pollSeconds = 20,
    manualToggleHotkey = { { "ctrl", "alt", "cmd" }, "A" },
  },
  jiggler = {
    enabled = true,
    intervalSeconds = 300,
    mode = "zen",
    whenExternalDisplay = true,
    requireClamshell = true,
    requireACPower = true,
    runImmediatelyOnEnable = false,
    showNotifications = true,
    toggleHotkey = { { "ctrl", "alt", "cmd" }, "J" },
  },
}
