return {
  logLevel = "info",
  notifications = {
    enabled = true,
  },
  ipc = {
    enabled = true,
    autoInstallCLI = false,
  },
  outlookAX = {
    enabled = true,
    defaultDepth = 6,
    defaultMaxNodes = 700,
  },
  reload = {
    watchConfigDir = true,
    hotkey = { { "cmd", "alt", "ctrl" }, "R" },
  },
  windowTiling = {
    enabled = true,
    screenMargin = 8,
    windowMargin = 8,
    centerSize = { w = 0.48, h = 0.82 },
    hotkeys = {
      left = { { "ctrl", "alt" }, "Left" },
      right = { { "ctrl", "alt" }, "Right" },
      bottomLeft = { { "ctrl", "alt", "cmd" }, "Down" },
      bottomRight = { { "ctrl", "alt", "cmd" }, "Up" },
      maximize = { { "ctrl", "alt" }, "Return" },
      center = { { "ctrl", "alt" }, "C" },
      nextScreen = { { "ctrl", "alt" }, "N" },
      previousScreen = { { "ctrl", "alt" }, "P" },
    },
  },
  keystrokes = {
    enabled = true,
    notifyOnShellFinish = false,
    hotkeys = {
      {
        mods = { "ctrl", "alt", "cmd" },
        key = "I",
        description = "Open iTerm",
        action = { type = "app", name = "iTerm" },
      },
      {
        mods = { "ctrl", "alt", "cmd" },
        key = "L",
        description = "Lock screen",
        action = { type = "hs", command = "lockScreen" },
      },
    },
  },
  dellKvm = {
    enabled = false,
    displayNameContains = "U2725QE",
    displayNumber = 1,
    inputs = { 15, 25 },
    keyfobVolumeUUID = "",
    bluetoothBinary = "/opt/homebrew/bin/blueutil",
    m1ddcBinary = "/opt/homebrew/bin/m1ddc",
    bluetoothDevices = {},
    connectDelaySeconds = 1.5,
    connectAttempts = 5,
    hotkey = { { "ctrl", "shift" }, "1" },
    showNotifications = true,
  },
  awake = {
    enabled = true,
    whenExternalDisplay = true,
    requireClamshell = true,
    requireACPower = true,
    preventDisplaySleep = false,
    showNotifications = true,
    pollSeconds = 20,
    manualToggleHotkey = { { "ctrl", "alt", "cmd" }, "A" },
  },
  jiggler = {
    enabled = true,
    intervalSeconds = 300,
    mode = "zen",
    whenExternalDisplay = false,
    requireClamshell = false,
    requireACPower = true,
    runImmediatelyOnEnable = false,
    showNotifications = true,
    toggleHotkey = { { "ctrl", "alt", "cmd" }, "J" },
  },
}
